New Analysis Class API
NREL/OpenOA pull request #252
Opened 2023-08-08 21:38 UTC by RHammond2

This PR addresses a longstanding issue with a lack of consistency between the analysis classes, and the differences between what is passed through `__init__()` vs `run()`. The updated paradigm is as follows:
- All run and __init__ arguments are now able to be passed to the __init__ method
- Only parameters that do not change the nature of what data is validated/checked for existence can be passed to `run()`. For example, the keyword argument `wind_direction_col` can be passed during initialization of `WakeLosses`, but not during the `run` method because we are changing the underlying data.
- Changing reanalysis products is still allowed in `run()` because this is about the sensitivity to long term weather data, and not pertaining to the underlying wind power plant data.

What this means is that run() can be used to iterate over permutations of an analysis on the same data, but if we need to swap out any data, e.g. different wind direction columns, additional SCADA columns, & etc., that should be considered to be an entirely new analysis, and therefore a new analysis class object is required.

2023-09-01 17:34 UTC, ejsimley requested changes
Hi Rob, I like the consistent format for initializing the analysis classes and specifying/changing parameters in the `run` methods! I have some minor questions and comments, but I think this is mostly ready to go. I will also update the doc strings for the wake losses class and/or change the default values for some of the arguments since the defaults without UQ weren't originally always the average of the default range with UQ.

2023-09-01 20:13 UTC, RHammond2 commented on openoa/analysis/aep.py
> +            if isinstance(gross_por_sum, pd.Series):
In the future pandas will just break for the original usage when `gross_por_sum` is a single element Series.

2023-09-01 20:14 UTC, RHammond2 commented on openoa/analysis/electrical_losses.py
> +        default=0.005, validator=validate_half_closed_0_1_right
Thanks for catching this, you're right, this is just missing the update after copying and pasting!

2023-09-01 20:17 UTC, RHammond2 commented on openoa/analysis/aep.py
> +        run more quickly.
This is likely just a remnant of old language that I just skipped over, but I'll update it while we're all here.

2023-09-01 20:21 UTC, RHammond2 commented on openoa/analysis/aep.py
> +        reanalysis_products: list[str] = None,
That's a great point! I think I originally envisioned this being as a subset of any that were originally provided, so if you add more, the method wouldn't work, but this was never actually implemented either.

I'm curious as to your thoughts here on whether it's an appropriate breaking of the paradigm or not. My own thoughts are that reanalysis data is already validated, so it's all there to be used, but at the same time it's still changing the nature of the analysis.

2023-09-01 20:25 UTC, RHammond2 commented on openoa/analysis/turbine_long_term_gross_energy.py
> +    def finalize_reanalysis_products(self):
We definitely could, and I think my main hangup is that it's not universally shared across the analysis classes, nor is it doing much to begin with, so I felt it was easier to just keep in the methods where it was needed. That said, I could be convinced if you think we should make another mixin class like with the `FromDictMixin` that manages the dictionary initialization processes.

2023-09-01 20:28 UTC, RHammond2 commented on openoa/analysis/_analysis_validators.py
> +        if not isinstance(value, (int, float)):
Fair point, I think I overthought it when I did that.

2023-09-01 20:30 UTC, RHammond2 commented on openoa/analysis/_analysis_validators.py
> +        if not 0.0 < value <= 1.0:
Excellent catch, thank you!

2023-09-12 15:37 UTC, jordanperr commented
Two thoughts:

**Thought 1:** How will this new paradigm extend to the workflow where analysis classes can "pull" data from an underlying datastore? For example, you might want to use MonteCarloAEP schema to pull all data necessary for a MonteCarloAEP from an ENTR warehouse. But then after pulling all the data, you might want some way to "exclude" one of the columns, say, to compare its impact on the AEP.

One possibility would be to extract the underlying PlantData object and then create two new MonteCarloAEP analyses using the same PlantData. Would that work?

I'm trying to think through if there might be a benefit to preserving the ability to just feed true/false into a flag in run().

**Thought 2:** Are PlantData and Analysis classes immutable? It didn't used to be. Please verify that no option in the run() function will mutate the PlantData and Analysis class. Or if they do, it should be noted somehow. The user will expect any combination of PlantData and Analysis class to be "run" multiple times with different options.

2023-09-25 22:22 UTC, RHammond2 commented on openoa/analysis/turbine_long_term_gross_energy.py
> +    def finalize_reanalysis_products(self):
@ejsimley I was thinking on this a bit more, and I created and another tool in `_analysis_validators` to do this. Let me know what you think.

2023-09-26 00:27 UTC, RHammond2 commented
> Two thoughts:
> 
> **Thought 1:** How will this new paradigm extend to the workflow where analysis classes can "pull" data from an underlying datastore? For example, you might want to use MonteCarloAEP schema to pull all data necessary for a MonteCarloAEP from an ENTR warehouse. But then after pulling all the data, you might want some way to "exclude" one of the columns, say, to compare its impact on the AEP.
> 
> One possibility would be to extract the underlying PlantData object and then create two new MonteCarloAEP analyses using the same PlantData. Would that work?
> 
> I'm trying to think through if there might be a benefit to preserving the ability to include/exclude data in run().
> 
> **Thought 2:** Are PlantData and Analysis classes immutable? It didn't used to be. Please verify that no option in the run() function will mutate the PlantData and Analysis class. Or if they do, it should be noted somehow. The user will expect any combination of PlantData and Analysis class to be "run" multiple times with different options.

@jordanperr thanks for the comments! I updated the description of the PR, but just to put it all in one place:
- Only `analysis_type` gets updated in `PlantData` from an analysis class, but the `analysis.plant` object is also created as a deep copy of the original, so
- you can create many new analysis classes to compare results of various modifications with ease
- Naturally, if you modify an analysis parameter, the analysis class itself will be updated, otherwise you'd not be able to rerun an analysis with a new variation of a parameter, but what isn't modified is the underlying data.
- The only thing excluded from the `run()` parameters are those that modify which data are validated, and therefore changing the fundamental basis of the analysis, with the exception of `reanalysis_products`.
- For pulling analysis requirements from a data store, we still don't explicitly support this outside of grabbing requirements schemas for the analysis types in `openoa/schema/` or from `ANALYSIS_REQUIREMENTS`

Let me know if I've missed anything here, or if you still have any reservations.

2023-09-27 20:42 UTC, merged